name: Deploy to ECR

on:
  push:
    branches: [ master ]


jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
        ECR_REPOSITORY: sample-flask
        IMAGE_TAG: latest
      run: |
        docker build -t 695372091606.dkr.ecr.us-east-1.amazonaws.com/sample-flask:latest .
        docker push 695372091606.dkr.ecr.us-east-1.amazonaws.com/sample-flask:latest
